name: klaytn-net-intelligence-api prod deploy workflow
on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: SessionForGhActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.ref_name }}
          BOOTNODES: ${{ secrets.BOOTNODES }}
          BOOTNODE_PORT: ${{ secrets.BOOTNODE_PORT }}
          RPC_HOST: ${{ secrets.RPC_HOST }}
          WS_SERVER: ${{ secrets.WS_SERVER }}
          WS_SECRET: ${{ secrets.WS_SECRET }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest . \
            --build-arg BOOTNODES=$BOOTNODES \
            --build-arg BOOTNODE_PORT=$BOOTNODE_PORT \
            --build-arg RPC_HOST=$RPC_HOST \
            --build-arg WS_SERVER=$WS_SERVER \
            --build-arg WS_SECRET=$WS_SECRET
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
